export const articles={
ko:[
{slug:"exam-overview",category:"시험 안내",title:"산업안전산업기사 시험 구조 한눈에 보기",description:"필기 5과목과 실기 복합형의 구조, 합격 기준, 준비 순서를 한 번에 정리합니다.",sections:[["필기는 100문항입니다","필기는 5과목에서 과목당 20문항씩 출제되는 객관식 4지 택일형입니다. 과목당 30분이므로 전체 기준 100문항, 150분입니다. 먼저 과목별 약점을 분리해 확인해야 시간 투자가 정확해집니다."],["과락과 평균을 함께 관리합니다","필기는 과목별 40점 이상이면서 전 과목 평균 60점 이상이어야 합니다. 강한 과목의 고득점만 노리기보다 모든 과목을 과락선 위로 올린 뒤 평균을 확보하는 전략이 안전합니다."],["실기는 판단 과정을 평가합니다","실기는 산업안전관리실무를 다루는 복합형입니다. 필답형 1시간 55점과 작업형 약 1시간 45점으로 구성되므로, 핵심어를 쓰는 연습과 현장 장면에서 위험요인을 판별하는 연습을 나누어 준비하세요."]]},
{slug:"written-format",category:"필기 전략",title:"5과목·100문항·150분을 운영하는 법",description:"과목별 20문항과 30분을 기준으로 과락을 막고 평균 60점을 만드는 실전 운영법입니다.",sections:[["한 과목에 오래 머물지 않습니다","과목별 배정 시간은 30분입니다. 첫 회독에서는 확실한 문항을 먼저 해결하고 계산이나 긴 판단이 필요한 문항에 표시를 남기세요. 정답률과 남은 시간을 동시에 지키는 방식입니다."],["오답은 원인별로 나눕니다","개념 미숙, 숫자 혼동, 문제 조건 누락, 단순 실수로 오답 원인을 구분하세요. 같은 오답이라도 처방이 다릅니다. 앱의 오답과 북마크 기능을 이용하면 반복되는 원인을 더 쉽게 찾을 수 있습니다."],["모의고사는 종료 시각까지 재현합니다","100문항을 실제 제한 시간 안에 풀고 과목별 점수까지 기록하세요. 평균이 60점을 넘어도 한 과목이 40점 아래면 합격할 수 없으므로, 총점과 과락 위험을 함께 점검해야 합니다."]]},
{slug:"accident-prevention",category:"필기 1과목",title:"산업재해 예방과 안전보건교육 공부법",description:"재해 원인, 예방 원칙, 안전보건교육을 연결해 암기보다 판단 중심으로 학습합니다.",sections:[["원인에서 대책으로 연결합니다","인적·물적·관리적 원인을 따로 외우는 데서 끝내지 말고 각 원인에 맞는 제거, 대체, 공학적 통제, 관리적 통제, 보호구 대책을 연결하세요."],["교육은 대상과 시점을 구분합니다","정기교육, 채용 시 교육, 작업내용 변경 시 교육, 특별교육은 대상과 실시 시점이 다릅니다. 문제의 작업자 상태와 작업 종류를 먼저 표시하면 비슷한 보기 사이의 혼동이 줄어듭니다."],["용어는 사례와 함께 복습합니다","재해 통계와 예방 원칙은 용어만 보면 쉽게 섞입니다. 한 개념마다 짧은 현장 사례를 붙여 어떤 조치가 선행되어야 하는지 설명해 보세요."]]},
{slug:"ergonomics-risk",category:"필기 2과목",title:"인간공학과 위험성평가를 하나의 흐름으로",description:"작업자 특성, 유해·위험요인 파악, 위험성 결정과 개선을 실제 작업 흐름으로 익힙니다.",sections:[["사람과 작업의 불일치를 찾습니다","자세, 반복, 중량물, 시야와 조작 장치의 배치가 작업자의 능력과 맞지 않을 때 오류와 부담이 커집니다. 인간공학 문제는 무엇이 불일치하는지부터 찾으세요."],["위험성평가는 순서를 지킵니다","사전 준비, 유해·위험요인 파악, 위험성 결정, 감소대책 수립과 실행, 기록과 공유의 흐름을 기준으로 사례를 정리하세요. 단계가 뒤섞인 보기를 가려내기 쉬워집니다."],["대책은 위험의 근원에 가깝게","가능하면 제거와 대체를 먼저 검토하고, 공학적·관리적 조치와 개인보호구를 순서대로 판단합니다. 보호구만 제시된 보기는 더 근본적인 대책이 가능한지 확인하세요."]]},
{slug:"machinery-safety",category:"필기 3과목",title:"기계·기구 및 설비 안전관리 핵심",description:"위험점, 방호장치, 점검과 정비 원칙을 기계의 운동과 작업자의 접근 관계로 정리합니다.",sections:[["위험점의 운동을 그립니다","협착, 절단, 물림, 회전 말림은 운동 방향과 작업자 접근 위치가 다릅니다. 간단한 화살표를 그려보면 방호장치의 목적이 선명해집니다."],["방호장치는 기능으로 구분합니다","접근을 막는 장치, 위험 상태에서 정지시키는 장치, 작업점과 손을 분리하는 장치를 기능 기준으로 비교하세요. 명칭만 외우면 적용 기계를 바꾼 보기에서 흔들리기 쉽습니다."],["정비 전 에너지 차단을 확인합니다","정지 버튼만 누르는 것과 에너지원을 차단·잠금·표시하는 것은 다릅니다. 청소, 점검, 수리 사례에서는 예기치 않은 기동과 잔류 에너지까지 확인해야 합니다."]]},
{slug:"electrical-chemical",category:"필기 4과목",title:"전기·화학설비 안전관리의 공통 원리",description:"감전, 정전기, 화재·폭발을 점화원과 에너지 통제 관점에서 비교합니다.",sections:[["전기는 경로와 차단으로 봅니다","감전 위험은 전압만이 아니라 인체를 통과하는 경로, 접촉 시간, 환경에 영향을 받습니다. 접지, 절연, 차단기의 역할을 각각 구분해 학습하세요."],["화재·폭발은 세 조건을 찾습니다","가연물, 산소, 점화원이 어떻게 만들어지는지 사례에서 표시하세요. 환기, 불활성화, 정전기 방지, 방폭 설비가 어느 조건을 낮추는 대책인지 연결하면 암기가 줄어듭니다."],["물질 정보는 작업 전에 확인합니다","물질안전보건자료와 경고표지는 저장, 취급, 누출, 소화, 보호구 선택의 근거입니다. 화학물질 문제에서는 물질 특성과 혼재 금지 여부를 먼저 확인하는 습관이 중요합니다."]]},
{slug:"construction-safety",category:"필기 5과목",title:"건설공사 안전관리 장면별 체크",description:"추락, 붕괴, 낙하·비래, 건설기계 위험을 작업 순서와 방호조치로 구분합니다.",sections:[["높이보다 추락 가능성을 봅니다","개구부, 작업발판, 사다리, 비계는 작업자의 이동과 작업 위치가 핵심입니다. 난간, 덮개, 안전대 부착설비 등 어떤 방호가 필요한지 장면별로 판단하세요."],["붕괴는 하중과 지지 상태를 봅니다","굴착면, 거푸집동바리, 흙막이, 해체 작업에서는 하중 변화와 지지 구조의 건전성이 중요합니다. 작업 순서 변경이나 부재 임의 제거가 어떤 위험을 만드는지 연결하세요."],["장비와 사람의 동선을 분리합니다","양중과 건설기계 작업에서는 작업반경, 유도자, 출입 통제, 신호체계를 함께 확인합니다. 장비 성능보다 충돌과 낙하물 노출을 줄이는 운영 조치가 자주 핵심이 됩니다."]]},
{slug:"practical-written",category:"실기 필답형",title:"필답형 답안을 채점 키워드로 설계하기",description:"55점 필답형에서 조건을 놓치지 않고 짧고 정확한 답안을 만드는 연습법입니다.",sections:[["질문의 동사를 먼저 표시합니다","쓰시오, 설명하시오, 계산하시오, 조치를 제시하시오는 요구하는 답의 형태가 다릅니다. 개수와 단위를 포함해 문제의 지시어를 먼저 표시하세요."],["한 문장에 한 조치를 씁니다","여러 대책을 한 문장에 섞으면 채점 요소가 흐려질 수 있습니다. 주체, 행동, 대상이 드러나는 짧은 문장으로 항목을 분리하세요."],["복습은 정답 문장 재현으로 합니다","눈으로 해설을 읽는 것보다 빈 종이에 제한 시간 안에 핵심어를 다시 쓰는 편이 효과적입니다. 빠진 키워드는 오답 목록에 누적해 반복하세요."]]},
{slug:"practical-video",category:"실기 작업형",title:"영상 작업형 위험요인 판별 순서",description:"45점 작업형에서 장면을 놓치지 않도록 사람·설비·환경·절차 순서로 관찰합니다.",sections:[["장면을 네 구역으로 스캔합니다","사람의 자세와 보호구, 기계의 운동부와 방호, 주변 환경, 작업 절차 순서로 화면을 확인하세요. 눈에 띄는 한 위험에만 집중하는 실수를 줄일 수 있습니다."],["위험요인과 조치를 짝지어 씁니다","무엇이 위험한지와 어떤 조치를 해야 하는지를 한 쌍으로 정리하세요. 모호한 표현보다 대상과 행동이 분명한 문장이 좋습니다."],["영상 없이도 장면을 말로 복원합니다","복습할 때 화면을 다시 보기 전에 기억나는 작업 위치, 설비 상태, 작업자 행동을 말로 설명해 보세요. 관찰 누락을 찾아내는 훈련이 됩니다."]]},
{slug:"eight-week-plan",category:"학습 계획",title:"8주 학습계획과 모의고사 운영",description:"개념, 과목별 문제, 실기 표현, 전범위 모의고사를 8주 안에 순환시키는 현실적인 계획입니다.",sections:[["1~3주는 필기 지도를 만듭니다","하루에 한 단원씩 핵심 개념을 정리하고 바로 소량의 문제로 확인하세요. 틀린 이유를 기록해 과목별 약점 지도를 만드는 기간입니다."],["4~6주는 필기와 실기를 연결합니다","과목별 문제량을 늘리는 동시에 필답형 핵심어와 작업형 관찰 훈련을 시작하세요. 같은 안전 원칙이 필기와 실기에서 어떻게 다르게 묻히는지 비교합니다."],["7~8주는 시험처럼 운영합니다","100문항을 150분 안에 풀고 과목별 과락 여부를 확인하세요. 실기는 정해진 시간 안에 답안을 직접 작성하고, 마지막 주에는 새로운 자료보다 반복 오답을 우선합니다."]]}
],
en:[
{slug:"exam-overview",category:"Exam guide",title:"Industrial Safety Engineer exam at a glance",description:"Understand the five written subjects, combined practical test, scoring thresholds, and a sensible preparation order.",sections:[["The written test has 100 questions","The written examination has five subjects, 20 four-option questions per subject, and 30 minutes per subject: 100 questions in 150 minutes. Track weaknesses by subject before allocating study time."],["Manage both floor and average","You need at least 40 points in every subject and a 60-point overall average. Bring every subject above the floor before relying on stronger subjects to lift the average."],["The practical test measures applied judgment","Industrial Safety Management Practice combines a one-hour 55-point written-response section and an approximately one-hour 45-point video work section. Train concise key-word answers and visual hazard recognition separately."]]},
{slug:"written-format",category:"Written strategy",title:"Managing five subjects, 100 questions, and 150 minutes",description:"Use the 20-question and 30-minute subject structure to avoid a subject failure while building a 60-point average.",sections:[["Do not stall on one subject","Answer confident items first and flag calculations or long judgments. The aim is to protect both accuracy and the time available for review."],["Classify the reason for each miss","Separate knowledge gaps, confused figures, missed conditions, and simple mistakes. Each cause needs a different correction; saved and missed-question review helps expose repeated patterns."],["Rehearse the full finish time","Complete 100 questions within the real limit and record each subject score. An average above 60 is not enough when one subject falls below 40."]]},
{slug:"accident-prevention",category:"Written subject 1",title:"Accident prevention and safety education",description:"Connect accident causes, prevention principles, and worker education through judgment rather than isolated memorization.",sections:[["Connect causes to controls","Link human, equipment, and management causes to elimination, substitution, engineering controls, administrative controls, and protective equipment."],["Separate audience and timing","Regular, hiring, changed-work, and special education differ in audience and timing. Mark the worker status and task before comparing similar options."],["Attach each term to a scenario","Statistics and prevention terminology blend together when learned alone. Give each concept a short workplace example and explain which intervention comes first."]]},
{slug:"ergonomics-risk",category:"Written subject 2",title:"Ergonomics and risk assessment as one workflow",description:"Learn worker fit, hazard identification, risk decisions, and improvements as a practical sequence.",sections:[["Find the mismatch","Posture, repetition, load, visibility, and control placement create risk when they exceed human capability. First identify what does not fit the worker."],["Respect the assessment sequence","Use preparation, hazard identification, risk evaluation, reduction measures, implementation, and records as the organizing flow."],["Move controls toward the source","Consider elimination and substitution first, then engineering and administrative measures, and finally personal protective equipment."]]},
{slug:"machinery-safety",category:"Written subject 3",title:"Machinery and equipment safety essentials",description:"Organize danger points, guards, inspection, and maintenance by machine motion and worker access.",sections:[["Draw the direction of motion","Crushing, cutting, nip points, and entanglement differ by motion and access. A quick arrow sketch clarifies what the guard must prevent."],["Classify guards by function","Compare devices that prevent access, stop a dangerous state, or separate hands from the point of operation instead of memorizing names alone."],["Isolate energy before maintenance","A stop button is not full energy isolation. Cleaning and repair scenarios require control of unexpected startup and stored energy."]]},
{slug:"electrical-chemical",category:"Written subject 4",title:"Shared principles of electrical and chemical safety",description:"Compare shock, static electricity, fire, and explosion through energy control and ignition prevention.",sections:[["View electricity as path and interruption","Shock risk depends on current path, duration, and environment as well as voltage. Keep grounding, insulation, and protective-device roles distinct."],["Find the fire triangle","Identify fuel, oxygen, and ignition in each scenario. Link ventilation, inerting, static control, and explosion-proof equipment to the condition each one reduces."],["Read hazard information before work","Safety data and labels guide storage, handling, spill response, firefighting, and PPE selection. Check material properties and incompatibilities first."]]},
{slug:"construction-safety",category:"Written subject 5",title:"A scene-based construction safety checklist",description:"Separate fall, collapse, falling-object, and equipment risks by work sequence and protective measure.",sections:[["Look for fall exposure, not height alone","Openings, platforms, ladders, and scaffolds require attention to movement and work position. Match guardrails, covers, or anchorage to the scene."],["For collapse, inspect load and support","Excavation, formwork shores, earth retaining, and demolition depend on changing loads and sound supports. Consider what happens when sequence or members change."],["Separate people from equipment paths","Lifting and mobile equipment require operating-radius control, spotters, access restriction, and clear signals to reduce collision and falling-object exposure."]]},
{slug:"practical-written",category:"Practical written",title:"Designing answers around scoring keywords",description:"Build short, precise responses for the 55-point written-response section without missing conditions.",sections:[["Mark the command verb","List, explain, calculate, and propose a measure require different answer forms. Mark the requested count and units before writing."],["Use one control per sentence","Separate measures so the actor, action, and target remain visible. Dense sentences can hide otherwise valid scoring elements."],["Recall the answer on blank paper","Timed retrieval is stronger practice than rereading. Add missing keywords to a repeat list until you can reproduce them."]]},
{slug:"practical-video",category:"Practical video",title:"A reliable order for spotting video hazards",description:"Scan people, equipment, environment, and procedure so the 45-point video section does not become guesswork.",sections:[["Scan four zones","Check worker posture and PPE, moving equipment and guards, the surrounding environment, and the work procedure in that order."],["Pair hazard and corrective action","State what is dangerous and the specific action that controls it. Clear targets and verbs are more useful than vague safety language."],["Reconstruct the scene from memory","Before replaying a clip, describe the location, equipment state, and worker action. The gaps reveal what your observation missed."]]},
{slug:"eight-week-plan",category:"Study plan",title:"An eight-week study and mock-exam plan",description:"Cycle concepts, subject practice, practical expression, and full simulations within eight focused weeks.",sections:[["Weeks 1–3: build the written map","Study one topic per day and verify it immediately with a small question set. Record the reason for each miss to create a subject weakness map."],["Weeks 4–6: connect written and practical","Increase subject practice while starting written-response keywords and video observation. Compare how the same safety principle appears in each format."],["Weeks 7–8: operate under exam conditions","Complete 100 questions in 150 minutes and inspect every subject floor. Write practical answers within a fixed time and prioritize repeated errors over new material in the final week."]]}
]};
